class_name MicroGames

const scenes: Array[PackedScene] = [
	# sort alphabetically
	preload("res://microgames/2048/main.tscn"),
	preload("res://microgames/alien_attack/main.tscn"),
	preload("res://microgames/ballon_popper/main.tscn"),
	preload("res://microgames/bugfix/bugfix.tscn"),
	preload("res://microgames/calc/calc.tscn"),
	preload("res://microgames/combing-cats/main.tscn"),
	preload("res://microgames/coin_collector/main.tscn"),
	preload("res://microgames/crabfight/crabfight.tscn"),
	preload("res://microgames/etch_a_sketch/main.tscn"),
	preload("res://microgames/flyswatter/fly_swatter.tscn"),
	preload("res://microgames/gardening/main.tscn"),
	preload("res://microgames/hello/hello.tscn"),
	preload("res://microgames/jeff_encounter/main.tscn"),
	preload("res://microgames/kaputtmachen/main.tscn"),
	preload("res://microgames/labyrinth/main.tscn"),
	preload("res://microgames/martian_mike/main.tscn"),
	preload("res://microgames/nox_box/main.tscn"),
	preload("res://microgames/pic_slide/main.tscn"),
	preload("res://microgames/questions/Main.tscn"),
	preload("res://microgames/responsibility/responsibility.tscn"),
	preload("res://microgames/skiing/main.tscn"),
	preload("res://microgames/skys/main.tscn"),
	preload("res://microgames/speedy_saucer/main.tscn"),
	preload("res://microgames/speed_golf/main.tscn"),
	preload("res://microgames/tilt/main.tscn"),
	preload("res://microgames/toast/main.tscn"),
]
